---
kind: pipeline
name: docker

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build

- name: test
  pull: always
  image: spritsail/docker-test
  settings:
    run: |
      salt-master --versions-report

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    login: {from_secret: docker_login}
    repo: frebib/salt-master
    tags:
    - latest
    - "%label io.spritsail.version.salt"
  when:
    branch:
    - master
    event:
    - push

---
kind: pipeline
name: update-readme

steps:
- name: dockerhub-readme
  pull: always
  image: jlesage/drone-push-readme
  settings:
    username: {from_secret: docker_username}
    password: {from_secret: docker_password}
    repo: frebib/salt-master
  when:
    branch:
    - master
    event:
    - push
---
kind: signature
hmac: 96d103ee7e47e81d18aac8512dbb4737d05ef81a00af1668d32e8fa93bf14a40

...
